[[main]]
  name = "Intro"
  url = "#top"
  weight = 10
  [main.params]
    id = "top-link"
    class = "icon solid fa-home"

[[main]]
  name = "Portfolio"
  url = "#portfolio"
  weight = 20
  [main.params]
    id = "portfolio-link"
    class = "icon solid fa-th"

[[main]]
  name = "About Me"
  url = "#about"
  weight = 30
  [main.params]
    id = "about-link"
    class = "icon solid fa-user"

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 40
  [main.params]
    id = "contact-link"
    class = "icon solid fa-envelope"
